config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li.nav-item= link_to 'Edit account', edit_user_registration_path, class: 'nav-link'
  %li.nav-item= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link'
- else
  %li.nav-item= link_to 'Sign in', new_user_session_path, class: 'nav-link'
  %li.nav-item= link_to 'Sign up', new_user_registration_path, class: 'nav-link'
- if user_signed_in?
  - if current_user.try(:admin?)
    %li.nav-item= link_to 'Users', users_path, class: 'nav-link'

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
.container
  %nav.navbar.navbar-dark.bg-inverse.nav-right
    %ul.nav.navbar-nav.clearfix
      %li.nav-item
        %button.navbar-toggler.hidden-sm-up.nav-link{"aria-controls" => "exCollapsingNavbar2", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", :type => "button"}
          \ &#9776;
    #exCollapsingNavbar2
      %ul.nav.navbar-nav= render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li
  - if current_user
    = link_to "Sign Out", user_session_path, method: :delete
  - else
    = link_to "Sing In", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Social Suggestions'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Social Suggestions'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/pages/about.html.haml
- content_for :title do
  About
%h3 About the Website
%p
  This web application was created with
  = link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/')
  from the #{link_to('RailsApps project', 'http://railsapps.github.io/')}.

app/views/users/_user.html.haml
%td
  = link_to user.email, user
%td
  = form_for(user) do |f|
    = f.select(:role, User.roles.keys.map {|role| [role.titleize,role]})
    = f.submit 'Change Role', :class => 'button-xs'
%td
  = link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user

app/views/users/index.html.haml
.container
  .row
    %h3 Users
    .column
      %table.table
        %tbody
          - @users.each do |user|
            %tr
              = render user

app/views/users/show.html.haml
%h3 User
%p
  Name: #{@user.name if @user.name}
%p
  Email: #{@user.email if @user.email}

app/views/visitors/index.html.haml
%h3 Welcome